hc = require("lib.hc")
ez = require("ez")
require("screen")
require("fps")
require("util")
require("managedlist")
require("spritesheet")
require("tilemap")
require("assets")
require("collisions")
require("pxparticles")
require("gui")
require("soundfx")
require("triggers")
require("dialogues")
require("savefile")
require("spells")
require("music")

require("entities.entities")
require("entities.hero")
require("entities.monsters")
require("entities.weapons")
require("entities.objects")
require("entities.npcs")
require("entities.entityparser")

require("controls.controller")
require("controls.key")
require("controls.input")

require("gamestates.gamestates")
require("gamestates.game")
require("gamestates.mainmenu")