hc = require("lib.hc")
require("screen")
require("fonts")
require("fps")
require("util")
require("managedlist")
require("spritesheet")
require("tilemap")
require("assets")
require("entities")

require("controls.controller")
require("controls.key")
require("controls.input")

require("gamestates.gamestates")
require("gamestates.game")